### ISSUE TITLE
v8 4.5 unshipped rest parameters

### ISSUE THREAD

**Issue by iefserge** [kesla/runtime-node-net#12]
Crashes in latest v8 4.5.107 (runtime kernel 0.1.13)
https://github.com/kesla/runtime-node-net/blob/master/lib/connect.js#L9
https://github.com/v8/v8-git-mirror/commit/4a4d83683dff9d2fc6bd17aa1f10d6104077467d

**Comment by facekapow** [comment]
Yep, just crashed for me too.
