### ISSUE TITLE
E_NO_ROUTE_TO_HOST

### ISSUE THREAD

**Issue by facekapow** [kesla/runtime-node-net#3]
When I run the tests, all tests pass without error. But, when I run it on my Initrd, I get `Error: E_NO_ROUTE_TO_HOST`. Any ideas why i'm getting this? (on OSX 10.10.3). BTW, this is for branch #2

**Comment by kesla** [comment]
not really no, what did you try and do?

**Comment by facekapow** [comment]
I installed `runtime-node-net` from the `http` branch and installed `http-node` (like the tests). I created a similar `runner.js` file that resolves `net` to `runtime-node-net` and `http` to `http-node`. Then, this is the rest of my `index.js`:

``` javascript
http.get('http://example.com', function(res) {
  console.log(res.statusCode);
});
```

**Comment by facekapow** [comment]
WAIT! I found a (sort of) workaround:

``` javascript
const server = net.createServer(function (socket) {
    socket.once('data', function (chunk) {
      socket.end();
      server.close();
      // code below logs '200'
      http.get('http://example.com', function (res) {
        console.log(res.statusCode);
      });
    });
  });

  server.listen(0, function () {
    const socket = net.createConnection(server.address().port);
    socket.write('beep');
    socket.end();
  });
```

HITCH: I get a de-optimization message  if I `require('runtimejs')`:
![screen shot](https://cloud.githubusercontent.com/assets/11756574/8193532/78641b2e-1443-11e5-8497-cf4b3264841c.png)

**Comment by kesla** [comment]
Hey, I'm super excited that you're taking a look at this - I'm not surprised that you hit a roadblock so let's try and figure it out... Could you get a test failing with the error that you're getting?

**Comment by iefserge** [comment]
@ArielAbreu deopt messages are ok (it's a v8 debug info)

**Comment by facekapow** [comment]
@kesla No, I guess it's because the tests already create servers. The code has to be wrapped in a basic runtime-node-net server to work. `console.log(res.statusCode)` works fine, but... `runtime.tty.print(res.statusCode)` doesn't do anything (not even any errors!).

**Comment by facekapow** [comment]
Wait! (again)...
In order to print `res.statusCode` using `runtime.tty.print()`, it must be converted to a string with `.toString()`. The follwing code prints `200` to the tty successfully:

``` javascript
'use strict';

const runtime = require('runtimejs');
const net = require('net');
const http = require('http');

const server = net.createServer(function (socket) {
  socket.once('data', function (chunk) {
    socket.end();
    server.close();
    http.get('http://example.com', function (res) {
      runtime.tty.print(res.statusCode.toString());
    });
  });
});

server.listen(8080, function () {
  const socket = net.createConnection(8080);
  socket.write('beep');
  socket.end();
});
```

that prints:
![screen shot](https://cloud.githubusercontent.com/assets/11756574/8195137/39eea9ee-144e-11e5-9e70-f35be506a251.png)

I believe this is an issue with runtimejs itself, `runtime.tty.print()` must only print strings to the tty.
Opening an issue in runtimejs...

**Comment by kesla** [comment]
@iefserge @ArielAbreu This looks like a real bug to me. So we should try and fix this.

**Comment by facekapow** [comment]
Yeah, maybe it initializes something in the system when it creates a server. I only have to create a server once and all other http operations work correctly.

**Comment by facekapow** [comment]
A <b>temporary</b> (permanent fix needed) fix would be to create and close a server in `runtime-node-net`'s `index.js`. Right now, i'm scouring runtime's `net` source code to find what exactly creating a server does that prevents this error. Until now, I haven't found anything.

**Comment by facekapow** [comment]
@iefserge You probably have an idea of what runtime's `net` does when it creates a server, right? Knowing what it does would be helpful to replicate it and avoid this error.
EDIT: Also what it does when it creates a connection might help.

**Comment by iefserge** [comment]
@ArielAbreu yep, going to look into this.

**Comment by facekapow** [comment]
@iefserge @kesla Do you know whether runtime creates a loopback? That might be the issue. I created a connection (not server) to localhost on any port (excect port 0, I get INVALID _PORT for port 0) and ended it (didn't even write) and http worked correctly.

**Comment by iefserge** [comment]
@ArielAbreu it was a DNS resolver issue, it tried to send a request before network was fully configured. Published an update that fixes it.

Was able to make an HTTP request and get the response, but got an assertion error after. URL I'm using is http://httpbin.org/ip

```
{
  "origin": "104.131.24.225"
}

Uncaught exception: /bundle.js:3524: AssertionError: false == true
AssertionError: false == true
    at IncomingMessage.responseOnEnd (/bundle.js:866:5)
    at IncomingMessage.EventEmitter.emit (/bundle.js:5500:17)
    at /bundle.js:7874:16
    at Item.run (/bundle.js:6050:14)
    at drainQueue (/bundle.js:6021:38)
```

My code:

``` js
http.get('http://httpbin.org/ip', function (res) {
  res.on('data', function(v) {
    console.log(v);
  });
});
```

**Comment by facekapow** [comment]
I've gotten the AssertionError as well, it's a bug in the DNS resolver as well, remove the "http://" from the URL and it goes away. A fix I use is to do a regex that returns everthing after the "://":

``` javascript
                   // my regex:
dns.resolve("http://www.example.com".match(/[a-z]\:\/\/([a-zA-Z\.]+)/)[1], {}, function(err, resdata) {
  // ...rest of code
});
```

`somestring.match(/[a-z]\:\/\/([a-zA-Z\.]+)/)[1]` doing that on the url should fix the AssertionError.

**Comment by facekapow** [comment]
Closing this issue as it has been fixed with a commit in runtime.
