### ISSUE TITLE
socket.destroy is not a function

### ISSUE THREAD

**Issue by facekapow** [kesla/runtime-node-net#8]
When using `http-node`'s `get` function, I get the error: "socket.destroy is not a function". <strike>It's ONLY when I use `res.on('end', function() { // ... });`</strike>. I traced it back to the end of `http-node`'s `socketOnEnd()` function. Apparently it calls `socket.destroy()`, with `socket` as `this`. This is also possibly the reason #4 doesn't work.

**Comment by kesla** [comment]
Yeah, this is still very much a WIP so I'm not surprised that you get this error. I can take a look at fixing this, thanks for reporting.

I'm pretty sure this is unrelated to #4, since #4 passes in node.js but fails in here - and that's without using the destory-method.
